# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab53bd13573c2392630ffcfa6d42a09aa050610770d40c15d8f3e20c5b14d8796d501e4c5873a4c2fba62abd3e64f7774ee6c598338c2cc4bde565787ce75e4

test:
  secret_key_base: ce2b5891f8c7291498bcfcdc8737800401f6392049894bcc5c74852e6afaff73e499451fa03cd71fa62f8ac18a41e913f67e46c3214ee5d6acd3d5a2f46f0914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
